### PR TITLE
FAB-10734 Add version command

### PR DESCRIPTION
**Pull request by TopJohn**
Add version command

Signed-off-by: TopJohn <xzj19922010@gmail.com>

### CODE REVIEW

**Comment by lehors** [comment]
So, this is an interesting addition but it is incomplete as it stands. We need a way to set the version to something different from "latest", don't we? In fabric this is done through some metadata variable set in the Makefile.
Please, add a short description to the title of your PRs.

**Comment by TopJohn** [comment]
> So, this is an interesting addition but it is incomplete as it stands. We need a way to set the version to something different from "latest", don't we? In fabric this is done through some metadata variable set in the Makefile.
> Please, add a short description to the title of your PRs.

I will add it into makefile, just wait.

**Comment by TopJohn** [comment]
> So, this is an interesting addition but it is incomplete as it stands. We need a way to set the version to something different from "latest", don't we? In fabric this is done through some metadata variable set in the Makefile.
> Please, add a short description to the title of your PRs.

I finished it.

**Comment by lehors** [comment]
Very nice, thank you! We should discuss what we want to set this to for now though. I'm not sure we're quite ready to label this as 1.0.

**Comment by TopJohn** [comment]
> Very nice, thank you! We should discuss what we want to set this to for now though. I'm not sure we're quite ready to label this as 1.0.

1.0 is just a placeholder. we have a lot to do brefore we release it.

**Pull request merged**
